sig-ddl: promote 'blacktear23' to active contributor:
pingcap/community pull request #357
Opened 2020-11-30 11:05 UTC by bb7133

@blacktear23 is very active in the past few months, his contributions
includes:

- [14 merged
PRs](https://github.com/pingcap/parser/pulls?q=is%3Apr+author%3Ablacktear23+is%3Aclosed) in TiDB repo and 10 of them are
DDL-related
- [2 merged PRs](https://github.com/pingcap/parser/pulls?q=is%3Apr+author%3Ablacktear23+is%3Aclosed) in parser
repo

2020-11-30 12:43 UTC, wjhuang2016 reviewed
LGTM

2020-11-30 13:10 UTC, AilinKid reviewed
LGTM

2020-12-01 03:02 UTC, hi-rustin commented
> LGTM

About the new robot command you can refer to https://prow.tidb.io/plugins?repo=pingcap%2Fcommunity.
The design doc: https://book.prow.tidb.io/plugins/lgtm.html

cc: @wjhuang2016  @AilinKid

2020-12-01 03:04 UTC, hi-rustin requested changes

2020-12-01 03:04 UTC, hi-rustin commented on special-interest-groups/sig-ddl/membership.json
> +	{
Better format it.

2020-12-01 03:16 UTC, wjhuang2016 commented
/lgtm

2020-12-01 05:09 UTC, hi-rustin commented
/hold 

Waiting fmt the JSON file.

2020-12-01 09:19 UTC, hi-rustin commented
/lgtm

2020-12-01 09:19 UTC, hi-rustin commented
/merge

2020-12-01 09:24 UTC, bb7133 commented on special-interest-groups/sig-ddl/membership.json
> +	{
Done, PTAL

2020-12-01 09:27 UTC, hi-rustin commented
/hold cancel

/assign @wjhuang2016 

You can `/merge` it now.

2020-12-02 10:42 UTC, wjhuang2016 commented
/merge

2020-12-02 10:43 UTC, AilinKid reviewed
LGTM

2020-12-02 10:43 UTC, AilinKid commented
/lgtm

2020-12-02 10:45 UTC, wjhuang2016 commented
/merge

2020-12-02 10:45 UTC, merged