vote for zyguan as maintainer
pingcap/community pull request #748
Opened 2023-03-27 02:22 UTC by cfzjywxk

2023-03-27 04:29 UTC, zz-jason approved these changes
LGTM

2023-03-27 05:48 UTC, disksing approved these changes

2023-03-28 03:26 UTC, bb7133 commented
/hold

2023-04-06 05:07 UTC, bb7133 approved these changes
LGTM

2023-04-06 06:23 UTC, bb7133 requested changes

2023-04-06 06:23 UTC, bb7133 commented on teams/tidb/membership.json
> +	"zyguan",
Need to remove `zyguan` from 'committers'.

2023-04-06 10:13 UTC, bb7133 approved these changes
LGTM

2023-04-06 10:13 UTC, bb7133 commented
/merge

2023-04-06 10:14 UTC, merged